packages:
- .
extra-deps:
- subdirs:
  - haskus-utils
  - haskus-utils-data
  - haskus-utils-types
  - haskus-utils-variant
  git: https://github.com/oofp/haskus-utlls_1.0_forked.git
  commit: c346272ec449155ea2e2a0fb3a4c3f3b707a13a5
- stm-containers-1.1.0.2
- stm-hamt-1.2.0.2
- primitive-extras-0.7.1
resolver: lts-13.15
